### PR TITLE
added support for bearer token method of authentication

### PR DESCRIPTION
**Pull request by rajatk16**

### CODE REVIEW

**Comment by rajatk16** [comment]
The New Version of Express Session requires us to set the resave and saveUninitialized.

As for the semi colons, its because of my Prettier Extension on VSCode (I do know Python but I am a JavaScript Developer)

The main thing is happening inside "policy". I have added an If Statement that checks if the keycloakConfig has "bearer-only" set to true. If so, then I am running keycloak.protect() (without passing anything to it.

**Comment by gitfish** [comment]
Hi Rajat,

Are you happy to take ownership of this repository? I can assign this to you if you like. I can also assign the npm repo for to you so you can publish it.

**Comment by rajatk16** [comment]
Hi Michael,

Sure I can take over the repository and the npm package as well.

My NPM username is geeky_writer_

**Comment by gitfish** [comment]
Ok - can you delete your forked repo first? I’ve added you as a maintainer
and removed myself for the bpm package.

Cheers.

**Comment by rajatk16** [comment]
I have deleted the forked repo!

Thanks once again for everything! :)

**Pull request merged**
